import { Component } from '@angular/core';

export enum QuestionType {
  "multipleChoice", "singleChoice"
}

export enum Difficulty {
  "EASY", "HARD"
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'self-assessment-tool';

  // global declaration of questions to be able to use it every component
  // has to be sorted after question group
  public static questionsTest: (MultipleChoiceQuestion | SingleChoiceQuestion)[] = [
    { textField: false, group: "Prozesse-Plan", title: "Frage zu Plan", type: QuestionType.multipleChoice, answers: [ { title: "Antwort 1", initialChecked: false, checked: true, points: -1 }, { title: "Antwort 2", initialChecked: false, checked: false, points: +2 }, { title: "Antwort 3", initialChecked: false, checked: true, points: 0 }]},
    { textField: false, group: "Prozesse-Plan", title: "Frage 1.1", type: QuestionType.multipleChoice, answers: [ { title: "Antwort 1", initialChecked: false, checked: false, points: +3 }, { title: "Antwort 2", initialChecked: false, checked: false, points: -1 }, { title: "Antwort 3", initialChecked: false, checked: true, points: +1 }]},
    {textField: true, text: "", 'title': 'Gibt es einen Plan für Social Media Analytics?',
      'group': 'Prozesse-Plan',
      'type': 0,
      'answers': [{'title': 'Antwortmöglichkeit 1 ',
        'points': 3,
        'checked': false,
        'initialChecked': false},
        {'title': 'Möglichkeit 2 ',
          'points': -2,
          'checked': false,
          'initialChecked': false},
        {'title': 'Möglichkeit 3',
          'points': -1,
          'checked': false,
          'initialChecked': false}]},
    { textField: true, text: "hallo", group: "Prozesse-Plan", title: "Frage 1.2", type: QuestionType.multipleChoice, answers: [ { title: "Antwort 1", initialChecked: false, checked: false, points: 0 }, { title: "Antwort 2", initialChecked: false, checked: true, points: 0 }, { title: "Antwort 3", initialChecked: false, checked: true, points: +4 }]},
    { textField: false, group: "Prozesse-Metriken", title: "Frage 2", type: QuestionType.multipleChoice, answers: [ { title: "Antwort 1", initialChecked: false, checked: false, points: -1 }, { title: "Antwort 2", initialChecked: false, checked: false, points: +2 }, { title: "Antwort 3", initialChecked: false, checked: true, points: +2 }]},
    { textField: false, group: "Technologie", title: "Frage 3", type: QuestionType.multipleChoice, answers: [ { title: "Antwort 1", initialChecked: false, checked: true, points: +1 }, { title: "Antwort 2", initialChecked: false, checked: false, points: -2, subquestions: [
          { textField: true, text: "", group: "Technologie", title: "Wie stehen Sie dazu?", type: QuestionType.multipleChoice, answers: [ { title: "Antwort 1", initialChecked: false, checked: false, points: -1 }, { title: "Antwort 2", initialChecked: false, checked: false, points: +2 }, { title: "Antwort 3", initialChecked: false, checked: true, points: +2 }]},
          { textField: true, text: "", group: "Technologie", title: "Wie stehen Sie dazu? Frage 2", type: QuestionType.multipleChoice, answers: [ { title: "Antwort 1", initialChecked: false, checked: false, points: -1 }, { title: "Antwort 2", initialChecked: false, checked: false, points: +2 }, { title: "Antwort 3", initialChecked: false, checked: true, points: +2 }]},
        ] }, { title: "Antwort 3", initialChecked: false, checked: true, points: +2 }]},
    { textField: true, text: "", group: "Organisation", title: "Single Choice Question", type: QuestionType.singleChoice, singleChoiceInitialAnswer: 0, singleChoiceAnswer: 0, answers: [ { title: "Antwort 1", initialChecked: false, checked: true, points: +2}, { title: "Antwort 2", initialChecked: false, checked: true, points: -1 }, { title: "Antwort 3", initialChecked: false, checked: true, points: -3 }]},
  ];

  public static questionsEasy: (MultipleChoiceQuestion | SingleChoiceQuestion)[] = [{'title': 'Gibt es eine Social Media Analytics Strategie mit klar formulierten Zielen?\xa0',
  'group': 'Prozesse-Planung',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Gab es eine Abwägung, welche Social Media Netzwerke für das eigene Unternehmen interessant sind?',
  'group': 'Prozesse-Planung',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Was sind die Ziele, welche man mit Social Media erreichen will?\xa0',
  'group': 'Prozesse-Planung',
  'type': 0,
  'textField': true,
  'text': '',
  'answers': [{'title': 'Markenbekanntheit steigern',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Dem Unternehmen eine einheitliche Corporate Identity geben',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Steigerung der eigenen Reichweite',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Neue Zielgruppen ansprechen',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nachhaltig den Umsatz steigern',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Kunden auf dem Laufenden halten',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Kosten für Marketing senken',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Kundenservice erhöhen',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird ein Social Media Analytics Tool genutzt?',
  'group': 'Prozesse-Planung',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Wurde eine Anforderungsanalyse gemacht, bevor ein Social Media Analytics Tools ausgewählt wurde?  ',
      'group': 'Prozesse-Planung',
      'type': 1,
      'textField': false
,
      'text': '',
      'answers': [{'title': 'Ja',
        'points': 10.0,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Nein',
        'points': 0.0,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Teilweise',
        'points': 5.0,
        'checked': false
  ,
        'initialChecked': false
}]}]},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Welche Form von Analytik wird genutzt?\xa0\xa0',
  'group': 'Prozesse-Planung',
  'type': 0,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Channel Analytics (Statistiken zum gesamten Channel, zb. Follower-Zahl, Reichweite, …)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Social Listening (Analyse von Erwähnungen unserer Marke, zb. Auf News-Seite)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Advertising Analytics (Analyse der Werbung, zb. Wie oft auf die Werbung geklickt wurde)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Content Analytics (Analyse einzelner Beiträge, zb. Likes, Kommentare, Engagement)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Customer Relationship Management Analytics (Analyse von Kundendaten, zb. Alter, Herkunft)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Content Management Analytics (Analyse des Content-Erstellungsprozess, zb. Kosten für die Erstellung eines Beitrags)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Ich weiß es nicht',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind unsere Social Media Kanäle miteinander verbunden und vermitteln Sie dieselbe Message?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Kontaktdaten bei Social Media Kanälen angegeben?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Gibt es einen Content-Release Plan?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Regelmäßig',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Unregelmäßig',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Situationsabhängig',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird ein Two-Way-Channel betrieben? (Der Versuch mit einzelnen Kunden direkt zu kommunizieren)',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Welche Form von Two-Way-Channel wird benutzt?\xa0',
      'group': 'Prozesse-Produktion',
      'type': 1,
      'textField': true,
      'text': '',
      'answers': [{'title': 'Kommentare',
        'points': 1.428,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Direktnachrichten',
        'points': 1.428,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Reviews ',
        'points': 1.428,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Personalisierte Werbung',
        'points': 1.428,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Personalisierter Content ',
        'points': 1.428,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Chatbots',
        'points': 1.428,
        'checked': false
  ,
        'initialChecked': false
}]}]},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Orientiert man sich beim Social Media Analytics Prozess am Return On Investment?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Welche Metriken werden gemessen?\xa0',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 0,
  'textField': true,
  'text': '',
  'answers': [{'title': 'Engagement',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Likes',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Follower',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Kommentare',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Reichweite',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Ist das Wissen vorhanden, welche Metriken wichtig für unsere Analyse sind?\xa0',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Metriken so gewählt, dass sie die wichtigen Kennzahlen möglichst einfach repräsentieren?\xa0',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Metriken auf die Korrelation mit anderen Metriken geprüft und wird die Korrelation möglichst vermieden?\xa0',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Metriken nach den Best Practices gewählt?\xa0',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Technologien wie AI verwendet?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Social Media Daten analysiert, um Kunden/Follower zu klassifizieren? (Alter/ Interessen/ Beruf, etc.)',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Was wird durch Analysen über die Kunden herausgefunden?\xa0',
      'group': 'Prozesse-Monitoring/Analytics',
      'type': 1,
      'textField': true,
      'text': '',
      'answers': [{'title': 'Geographie',
        'points': 0.83,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Demographie',
        'points': 0.83,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Geschlecht',
        'points': 0.83,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Alter',
        'points': 0.83,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Nationalität',
        'points': 0.83,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Religion',
        'points': 0.83,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Beruf/Arbeitgeber',
        'points': 0.83,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Familienstand',
        'points': 0.83,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Einstellung zum Unternehmen',
        'points': 0.83,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Interessen',
        'points': 0.83,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Sozialer Kreis',
        'points': 0.83,
        'checked': false
  ,
        'initialChecked': false
}]}]},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Welche Social Media Channel nutzt die Community überwiegend?\xa0',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 0,
  'textField': true,
  'text': '',
  'answers': [{'title': 'Instagram',
    'points': 0.714,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Facebook',
    'points': 0.714,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Twitter',
    'points': 0.714,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Pinterest',
    'points': 0.714,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'TikTok',
    'points': 0.714,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'LinkedIn',
    'points': 0.714,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird versucht den Grund hinter Social Media Trends auszumachen?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird die Bedeutung von Aktionen zwischen den Social Media Plattformen unterschieden? (Beispielsweise, dass Likes auf Instagram weniger Wert haben als auf Pinterest, da die Hemmschwelle für ein Instagram-Like geringer ist)',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird bei der Content-Analyse zwischen bezahlten und organischen Posts unterschieden?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden für die Analysen mehrere Datenquellen integriert?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Kommentare ausgewertet, beispielsweise durch Sentiment-Analysis, um Kundenfeedback zu analysieren? (zb. positive/neutrale/negative Kommentare)',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Führen wir Analysen durch, welche Hashtags am effektivsten sind?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Markierungen bzw. Erwähnungen unserer Firma wahrgenommen?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Dashboards dem Use Case individuell angepasst?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird beim Report die Stellung gegenüber wichtigen Konkurrenten aufgezeigt?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wie werden Metriken dargestellt?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Einfach',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Komplex (bspw. auf mehrere Graphen aufgeteilt)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Einfach und komplex (situationsbedingt)',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Gibt es ein Verständnis für die Herkunft/Quellen der verwendeten Daten?',
  'group': 'Prozesse-Datenmanagement',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird Integrität der Daten sichergestellt?',
  'group': 'Prozesse-Datenmanagement',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wo sind die Daten gespeichert?',
  'group': 'Prozesse-Datenmanagement',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Alle Daten werden intern gespeichert',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Alle Daten werden extern gespeichert',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Daten werden hybrid intern und extern gespeichert',
    'points': 3.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Generieren wir Leads? (Generierung von Kundendaten)',
  'group': 'Prozesse-Datenmanagement',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Ist die Erstellung von Reports mit dem Tool möglich?',
  'group': 'Prozesse-Technologien',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Welche Daten kann das Tool auswerten?\xa0',
  'group': 'Prozesse-Technologien',
  'type': 0,
  'textField': true,
  'text': '',
  'answers': [{'title': 'Auswertung für Facebook',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Auswertung für Instagram',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Auswertung für Twitter',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Auswertung für LinkedIn',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Auswertung für TikTok',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Conversion Rates über Links',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Kommentare',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Sharing',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Likes',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Reposts',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Anzahl von Leads',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Wie oft Werbung angeschaut wurde',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Technologien wie AI mit unserem Tool möglich?',
  'group': 'Prozesse-Technologien',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Kann das Tool automatisch Beiträge erstellen, die unserem Content entsprechen?',
  'group': 'Prozesse-Technologien',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Ja',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Gibt es beim Veröffentlichen von Content ein konkretes Rechteverwaltungssystem? (Administratoren, Moderatoren, Redakteure)',
  'group': 'Prozesse-Technologien',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wer macht die Analysen?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Intern',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Wie ist die Abteilung aufgebaut?\xa0',
      'group': 'Prozesse-Organisation',
      'type': 1,
      'textField': false
,
      'text': '',
      'answers': [{'title': 'Die Analyse wird von einer Person gemacht',
        'points': 0.0,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Die Analyse wir von einer kleinen Arbeitsgruppe gemacht',
        'points': 0.0,
        'checked': false
  ,
        'initialChecked': false
},
       {'title': 'Es gibt für die einzelnen Bereiche (Posts, Listening, …) Experten',
        'points': 0.0,
        'checked': false
  ,
        'initialChecked': false
}]}]},
   {'title': 'Extern',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wie erfahren sind die Analysten/ das Analysten-Team?\xa0',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Unerfahren',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Erfahren',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Experten',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Partnerbeziehungen betrieben?\xa0',
  'group': 'Prozesse-Organisation',
  'type': 0,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja, mit Tool, um Daten über Konkurrenten oder die Branche zu erhalten',
    'points': 3.33,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Ja, mit Social Media Plattform, um erweiterte Funktionen (z.B. LinkedIn Suchfunktion) oder kostenpflichtige Daten zu erhalten',
    'points': 3.33,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Ja, mit Agentur, um Brancheninformationen oder Analysen bereitgestellt zu bekommen',
    'points': 3.33,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Gibt es einen Projektmanagementprozess für Social Media Analytics?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja. Es gibt eine Planungs-, Umsetzungs- und Evaluationsphase',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein. Social Media Analytics wird ohne Management und ohne konkreten Plan gemacht',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise. Zuständige Personen kennen den Input, aller beteiligten Mitarbeitern und den gewünschten Output',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Prozesse ...',
  'group': 'Prozesse-Organisation',
  'type': 0,
  'textField': false,
  'text': '',
  'answers': [{'title': 'sind einheitlich',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'sind vorrauschaubar',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'werden mittels Kennzahlen ausgewertet',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'werden dokumentiert',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden die Social Media Analytics Prozess-Deadlines eingehalten?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Stakeholder in den Prozess einbezogen?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird die Qualität der Prozesse sichergestellt?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wissen ist transparent und kann jeder Zeit abgerufen werden?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]}]

  public static questionsHard: (MultipleChoiceQuestion | SingleChoiceQuestion)[] = [{'title': 'Gibt es eine Social Media Analytics Strategie mit klar formulierten Zielen?\xa0',
  'group': 'Prozesse-Planung',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Gab es eine Abwägung, welche Social Media Netzwerke für das eigene Unternehmen interessant sind?',
  'group': 'Prozesse-Planung',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Was sind die Ziele, welche man mit Social Media erreichen will?\xa0',
  'group': 'Prozesse-Planung',
  'type': 0,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Markenbekanntheit steigern',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Gibt es Strategien zur Erreichung der ausgewählten Social Media Ziele?',
      'group': 'Prozesse-Planung',
      'type': 0,
      'textField': false,
      'text': '',
      'answers': [{'title': 'Ja',
        'points': 10.0,
        'checked': false,
        'initialChecked': false},
       {'title': 'Nein',
        'points': 0.0,
        'checked': false,
        'initialChecked': false}]}]},
   {'title': 'Steigerung der eigenen Reichweite',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Neue Zielgruppen ansprechen',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nachhaltig den Umsatz steigern',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Kunden auf dem Laufenden halten',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Kosten für Marketing senken',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Kundenservice erhöhen',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': '',
    'points': 1.11,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird ein Social Media Analytics Tool genutzt?',
  'group': 'Prozesse-Planung',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Wurde eine Anforderungsanalyse gemacht, bevor ein Social Media Analytics Tools ausgewählt wurde?  ',
      'group': 'Prozesse-Planung',
      'type': 1,
      'textField': false,
      'text': '',
      'answers': [{'title': 'Ja',
        'points': 10.0,
        'checked': false,
        'initialChecked': false},
       {'title': 'Nein',
        'points': 0.0,
        'checked': false,
        'initialChecked': false},
       {'title': 'Teilweise',
        'points': 5.0,
        'checked': false,
        'initialChecked': false}]}]},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Welche Form von Analytik wird genutzt?\xa0\xa0',
  'group': 'Prozesse-Planung',
  'type': 0,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Channel Analytics (Statistiken zum gesamten Channel, zb. Follower-Zahl, Reichweite, …)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Social Listening (Analyse von Erwähnungen unserer Marke, zb. Auf News-Seite)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Advertising Analytics (Analyse der Werbung, zb. Wie oft auf die Werbung geklickt wurde)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Content Analytics (Analyse einzelner Beiträge, zb. Likes, Kommentare, Engagement)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Customer Relationship Management Analytics (Analyse von Kundendaten, zb. Alter, Herkunft)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Content Management Analytics (Analyse des Content-Erstellungsprozess, zb. Kosten für die Erstellung eines Beitrags)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Ich weiß es nicht',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wie erfolgt die Planung?\xa0',
  'group': 'Prozesse-Planung',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Reaktiv',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Proaktiv',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind unternehmensinterne Social Media Kanäle miteinander verbunden?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Vermitteln die unterschiedlichen Kanäle dieselbe Message?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Kontaktdaten bei Social Media Kanälen angegeben?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Gibt es einen Content-Release Plan?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Regelmäßig',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Unregelmäßig',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Situationsabhängig',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Beiträge repostet, von denen das Unternehmen profitieren könnte?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 1.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Gruppen genutzt, welche für das Unternehmen relevante Beträge veröffentlichen?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Werden in diesen Gruppen selbst Beiträge veröffentlicht?',
      'group': 'Prozesse-Produktion',
      'type': 1,
      'textField': false,
      'text': '',
      'answers': [{'title': 'Ja',
        'points': 2.0,
        'checked': false,
        'initialChecked': false},
       {'title': 'Nein',
        'points': 0.0,
        'checked': false,
        'initialChecked': false}]}]},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Posts professionell gestaltet?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird ein Two-Way-Channel betrieben? (Der Versuch mit einzelnen Kunden direkt zu kommunizieren)',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Welche Form von Two-Way-Channel wird benutzt?',
      'group': 'Prozesse-Produktion',
      'type': 1,
      'textField': true,
      'text': '',
      'answers': [{'title': 'Kommentare',
        'points': 1.428,
        'checked': false,
        'initialChecked': false},
       {'title': 'Direktnachrichten',
        'points': 1.428,
        'checked': false,
        'initialChecked': false},
       {'title': 'Reviews',
        'points': 1.428,
        'checked': false,
        'initialChecked': false},
       {'title': 'Personalierte Werbung',
        'points': 1.428,
        'checked': false,
        'initialChecked': false},
       {'title': 'Peronaliserter Content',
        'points': 1.428,
        'checked': false,
        'initialChecked': false},
       {'title': 'Chatbots',
        'points': 1.428,
        'checked': false,
        'initialChecked': false}]}]},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird Community Management betrieben, um eine bessere Interaktion mit der Community zu erreichen?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Smart-Labels benutzt(Werbeparameter für Facebook und Instagram)?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Orientiert man sich beim Social Media Analytics Prozess am Return On Investment?',
  'group': 'Prozesse-Produktion',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Welche Metriken werden gemessen?\xa0',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 0,
  'textField': true,
  'text': '',
  'answers': [{'title': 'Engagement',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Likes',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Follower',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Kommentare',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Ist das Wissen vorhanden, welche Metriken wichtig für unsere Analyse sind?\xa0',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 0,
  'textField': true,
  'text': '',
  'answers': [{'title': 'Reichweite',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Metriken auf die Unternehmensziele abgestimmt?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden default (Standard) oder custom (Benutzerdefinierte) Metriken verwendet?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Default',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Ist die Auswahl der Metriken begründet?',
      'group': 'Prozesse-Monitoring/Analytics',
      'type': 1,
      'textField': false,
      'text': '',
      'answers': [{'title': 'Ja',
        'points': 0.0,
        'checked': false,
        'initialChecked': false},
       {'title': 'Nein',
        'points': 0.0,
        'checked': false,
        'initialChecked': false}]}]},
   {'title': 'Custom',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Metriken so gewählt, dass sie die wichtigen Kennzahlen möglichst einfach repräsentieren?\xa0',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Metriken auf die Korrelation mit anderen Metriken geprüft und wird die Korrelation möglichst vermieden?\xa0',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Metriken nach den Best Practices gewählt?\xa0',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Welche Best-Practices wurden gewählt?',
      'group': 'Prozesse-Monitoring/Analytics',
      'type': 1,
      'textField': false,
      'text': '',
      'answers': [{'title': 'Es werden Best Practices von vergleichbaren Unternehmen herangezogen',
        'points': 0.0,
        'checked': false,
        'initialChecked': false},
       {'title': 'Es werden allgemeine Best Practices herangezogen',
        'points': 0.0,
        'checked': false,
        'initialChecked': false}]}]},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird mit echten oder geschätzten Metriken gearbeitet und ist der Unterschied bekannt?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Es gibt keine Unterscheidung von echten und geschätzten Metrics.',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Es gibt ein Verständnis für den Unterschied.',
    'points': 1.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Es gibt ein Verständnis für den Unterschied und sie werden möglichst effektiv eingesetzt.',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Welche Stufen der Analytik werden verwendet?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 0,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Deskriptiv (beschreibend)',
    'points': 3.33,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Prädiktiv (vorhersagend)',
    'points': 3.33,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Präskriptiv (vorschlagend)',
    'points': 3.33,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Gibt es eine Strategie bei der Analyse?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Wie ist die gewählte Strategie?',
      'group': 'Prozesse-Monitoring/Analytics',
      'type': 1,
      'textField': false,
      'text': '',
      'answers': [{'title': 'Strategie ist einheitlich im Unternehmen',
        'points': 0.0,
        'checked': false,
        'initialChecked': false},
       {'title': 'Strategie ist unterschiedlich innerhalb des Unternehmens',
        'points': 0.0,
        'checked': false,
        'initialChecked': false}]}]},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Technologien wie AI verwendet?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Social Media Daten analysiert, um Kunden/Follower zu klassifizieren? (Alter/ Interessen/ Beruf/ …) ',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Was wird durch Analysen über die Kunden herausgefunden?\xa0',
      'group': 'Prozesse-Monitoring/Analytics',
      'type': 1,
      'textField': true,
      'text': '',
      'answers': [{'title': 'Geographie',
        'points': 0.416,
        'checked': false,
        'initialChecked': false},
       {'title': 'Demographie',
        'points': 0.416,
        'checked': false,
        'initialChecked': false},
       {'title': 'Geschlecht',
        'points': 0.416,
        'checked': false,
        'initialChecked': false},
       {'title': 'Alter',
        'points': 0.416,
        'checked': false,
        'initialChecked': false},
       {'title': 'Nationalität',
        'points': 0.416,
        'checked': false,
        'initialChecked': false},
       {'title': 'Religion',
        'points': 0.416,
        'checked': false,
        'initialChecked': false},
       {'title': 'Beruf/Arbeitgeber',
        'points': 0.416,
        'checked': false,
        'initialChecked': false},
       {'title': 'Familienstand',
        'points': 0.416,
        'checked': false,
        'initialChecked': false},
       {'title': 'Einstellung zum Unternehmen',
        'points': 0.416,
        'checked': false,
        'initialChecked': false},
       {'title': 'Interessen',
        'points': 0.416,
        'checked': false,
        'initialChecked': false},
       {'title': 'Sozialer Kreis',
        'points': 0.416,
        'checked': false,
        'initialChecked': false}]}]},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Welche Social Media Channel nutzt die Community überwiegend?\xa0',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 0,
  'textField': true,
  'text': '',
  'answers': [{'title': 'Instagram',
    'points': 0.714,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Facebook',
    'points': 0.714,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Twitter',
    'points': 0.714,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Pinterest',
    'points': 0.714,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'TikTok',
    'points': 0.714,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'LinkedIn',
    'points': 0.714,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird die Stellung am Markt durch (Competitive) Benchmarking analysiert?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wie wird in den Medien über unser Unternehmen geredet?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Positiv',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Negativ',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Neutral',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird versucht den Grund hinter Social Media Trends auszumachen?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird die Bedeutung von Aktionen zwischen den Social Media Plattformen unterschieden? (Beispielsweise, dass Likes auf Instagram weniger Wert haben als auf Pinterest, da die Hemmschwelle für ein Instagram-Like geringer ist)',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird bei der Content-Analyse zwischen bezahlten und organischen Posts unterschieden?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden für die Analysen mehrere Datenquellen integriert?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Wie werden die Datenquellen integiert?',
      'group': 'Prozesse-Monitoring/Analytics',
      'type': 1,
      'textField': false,
      'text': '',
      'answers': [{'title': 'Es werden mehrere Datenquellen aus verschiedenen Social Media Plattformen verbunden',
        'points': 0.0,
        'checked': false,
        'initialChecked': false},
       {'title': 'Es werden Datenquellen aus Social Media Plattformen und Daten aus anderen Bereichen des Unternehmens für die Analysen verbunden',
        'points': 2.0,
        'checked': false,
        'initialChecked': false}]}]},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Kommentare ausgewertet, beispielsweise durch Sentiment-Analysis, um Kundenfeedback zu analysieren? (zb. positive/neutrale/negative Kommentare)',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird die Periode/Zeitraum der Daten bei Analysen berücksichtigt?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird die Frequentierung der Daten bei Analysen berücksichtigt?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Analysen durchgeführt, welche Hashtags am effektivsten sind?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Klout-Scores genutzt? (Bewertung von Influencers im Hinblick auf Verhalten und Reichweite)',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Markierungen bzw. Erwähnungen unserer Firma wahr genommnen?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Dashboards dem Use Case individuell angepasst?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Reports für Stakeholder individuell angepasst, um die Aussagekraft zu fördern?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Reports durch Erklärungen so ergänzt, dass Außenstehende (Stakeholder) folgen können?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Ist über ein Teilfunktion möglich, sensible Daten für externe Kunden automatisch verbergen?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird beim Report die Stellung gegenüber wichtigen Konkurrenten aufgezeigt?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden möglichst aussagekräftige und passende Graphen für die Darstellung der Metriken genutzt?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wie werden Metriken dargestellt?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Einfach',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Komplex (bspw. auf mehrere Graphen aufgeteilt)',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Einfach und komplex (situationsbedingt)',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden bei der Visualisierung die Grundlagen der Kommunikation (Sender, Medium, Empfänger, Feedback) berücksichtigt?',
  'group': 'Prozesse-Monitoring/Analytics',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Gibt es ein Verständnis für die Herkunft/Quellen der verwendeten Daten?',
  'group': 'Prozesse-Datenmanagement',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Stellen unsere Tools zusätzliche Daten bereit, beispielsweise den Vergleich zu Konkurrenten und nutzen wir diese Daten?',
  'group': 'Prozesse-Datenmanagement',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Werden diese Daten genutzt?',
      'group': 'Prozesse-Datenmanagement',
      'type': 1,
      'textField': false,
      'text': '',
      'answers': [{'title': 'Ja',
        'points': 2.0,
        'checked': false,
        'initialChecked': false},
       {'title': 'Nein',
        'points': 0.0,
        'checked': false,
        'initialChecked': false}]}]},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird die Integrität von geschätzten Daten (bspw. Instagram Reichweite) durch den Vergleich zu echten Daten sichergestellt?',
  'group': 'Prozesse-Datenmanagement',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wo sind die Daten gespeichert?',
  'group': 'Prozesse-Datenmanagement',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Alle Daten werden intern gespeichert',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Alle Daten werden extern gespeichert',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Daten werden hybrid intern und extern gespeichert',
    'points': 3.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Generieren wir Leads? (Generierung von Kundendaten)',
  'group': 'Prozesse-Datenmanagement',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Welche Tools werden für Social Media Analytics verwendet?',
  'group': 'Prozesse-Technologien',
  'type': 0,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Keine Tools',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Customer Relationship Management Analytics Tool',
    'points': 1.428,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Content Management Analytics Tool',
    'points': 1.428,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Advertising Analytics Tool',
    'points': 1.428,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Listening Tool',
    'points': 1.428,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Content Analytics Tool',
    'points': 1.428,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Channel Analytics Tool',
    'points': 1.428,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Hybrid Tool',
    'points': 1.428,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Custom Metriken mit dem Tool möglich?',
  'group': 'Prozesse-Technologien',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Wie erfolgt die Einbindung von Custom Metriken? ',
      'group': 'Prozesse-Technologien',
      'type': 1,
      'textField': false,
      'text': '',
      'answers': [{'title': 'Mit Point-And-Click',
        'points': 2.0,
        'checked': false,
        'initialChecked': false},
       {'title': 'Mit Code',
        'points': 0.0,
        'checked': false,
        'initialChecked': false}]}]},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Ist Community Management mit dem Tool möglich?',
  'group': 'Prozesse-Technologien',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Welche Daten kann das Tool auswerten?\xa0',
  'group': 'Prozesse-Technologien',
  'type': 0,
  'textField': true,
  'text': '',
  'answers': [{'title': 'Auswertung für Facebook',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Auswertung für Instagram',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Auswertung für Twitter',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Auswertung für LinkedIn',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Auswertung für TikTok',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Conversion Rates über Links',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Kommentare',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Sharing',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Likes',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Reposts',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Anzahl von Leads',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Wie oft Werbung angeschaut wurde',
    'points': 0.77,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Technologien wie AI mit unserem Tool möglich?',
  'group': 'Prozesse-Technologien',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Technologien wie AI mit unserem Tool möglich?',
  'group': 'Prozesse-Technologien',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Kann das Tool automatisch Beiträge erstellen, die dem Content entsprechen?',
  'group': 'Prozesse-Technologien',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Ja',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Gibt es beim Veröffentlichen von Content ein konkretes Rechteverwaltungssystem? (Administratoren, Moderatoren, Redakteure)',
  'group': 'Prozesse-Technologien',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wer macht die Analysen?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Intern',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Extern',
    'points': 7.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wie ist die Abteilung aufgebaut?\xa0',
  'group': 'Single',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Die Analyse wird von einer Person gemacht',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wie erfahren sind die Analysten/ das Analysten-Team?\xa0',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Unerfahren',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Erfahren',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Experten',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Betreiben wir Partnerbeziehungen?\xa0',
  'group': 'Prozesse-Organisation',
  'type': 0,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja, mit Tool, um Daten über Konkurrenten oder die Branche zu erhalten',
    'points': 3.33,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Partnerbeziehungen betrieben?\xa0',
  'group': 'Prozesse-Organisation',
  'type': 0,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja, mit Social Media Plattform, um erweiterte Funktionen (z.B. LinkedIn Suchfunktion) oder kostenpflichtige Daten zu erhalten',
    'points': 3.33,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Ja, mit Agentur, um Brancheninformationen oder Analysen bereitgestellt zu bekommen',
    'points': 3.33,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Gibt es einen Projektmanagementprozess für Social Media Analytics?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja. Es gibt eine Planungs-, Umsetzungs- und Evaluationsphase',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein. Social Media Analytics wird ohne Management und ohne konkreten Plan gemacht',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise. Zuständige Personen kennen den Input, aller beteiligten Mitarbeitern und den gewünschten Output',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Strategien dynamisch angepasst?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Sind Best Practices und Richtlinien bezüglich der Arbeit eines Analysten vorgegeben, oder überlässt man dem Analysten die gesamte Handlungsmacht?  ',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Prozesse ...',
  'group': 'Prozesse-Organisation',
  'type': 0,
  'textField': false,
  'text': '',
  'answers': [{'title': 'wiederholen sich',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'sind einheitlich',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'sind vorrauschaubar',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'werden mittels Kennzahlen ausgewertet',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'werden dokumentiert',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden die Social Media Analytics Prozess-Deadlines eingehalten?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': [{'title': 'Bleibt am Ende des Prozesses genug Zeit für Feedback?',
      'group': 'Prozesse-Organisation',
      'type': 1,
      'textField': false,
      'text': '',
      'answers': [{'title': 'Ja',
        'points': 5.0,
        'checked': false,
        'initialChecked': false},
       {'title': 'Nein',
        'points': 0.0,
        'checked': false,
        'initialChecked': false},
       {'title': 'Teilweise',
        'points': 2.0,
        'checked': false,
        'initialChecked': false}]}]},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Werden Stakeholder in den Prozess einbezogen?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird die Qualität der Prozesse sichergestellt?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Ziel ist es Innovationen voranzutreiben?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 2.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 1.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wissen ist transparent und kann jeder Zeit abgerufen werden?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 10.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Teilweise',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]},
 {'title': 'Wird sich in der Organisation an Best Practices orientiert?',
  'group': 'Prozesse-Organisation',
  'type': 1,
  'textField': false,
  'text': '',
  'answers': [{'title': 'Ja',
    'points': 5.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []},
   {'title': 'Nein',
    'points': 0.0,
    'checked': false,
    'initialChecked': false,
    'subquestions': []}]}]

  state: Question[] = [];
  public static progress: number;

  constructor() {
    AppComponent.progress = 0;
  }

  public getProgress(): number {
    return AppComponent.progress;
  }
}

interface Question {
  title: string;
  type: QuestionType;
  answers: Answer[];
  group: string;
  showSubquestion?: boolean;
  textField: boolean;
  text?: string;
}

export interface SingleChoiceQuestion extends Question {
  type: QuestionType.singleChoice;
  singleChoiceAnswer: number;
  singleChoiceInitialAnswer: number;
}

export interface MultipleChoiceQuestion extends Question {
  type: QuestionType.multipleChoice;
}

export interface Answer {
  title: string;
  initialChecked: boolean;
  checked: boolean;
  points: number;
  subquestions?: (SingleChoiceQuestion | MultipleChoiceQuestion)[];
}
